

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"

    environment:
      - GO_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend